config/routes.rb
BrowserUpload::Application.routes.draw do
  resources :uploads

  root :to => "uploads#index"

  resource :uploads
  

end

app/models/upload.rb
class Upload < ActiveRecord::Base
	def url
		# HINT: pretty terrible.
		AWS_HOST + self.key + '/' + self.filename
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  require 'base64'
  require 'openssl'
  require 'digest/sha1'

  before_action :set_upload, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    # redirect_to @upload.url
  end

  # GET /uploads/new
  def new
    @callback = uploads_url
    @key = SecureRandom.base64(16).gsub(/[\/\+]/, 'X').gsub(/=+$/, '').downcase
    @policy = s3_policy(@key, AWS_BUCKET)
    @signature = s3_sign_policy(@policy, AWS_SECRET_ACCESS_KEY)
    @id = AWS_ID
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render action: 'show', status: :created, location: @upload }
      else
        format.html { render action: 'new' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    pp params
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    # Actually removing it from amazon if left as an exercise for the reader...
    # HINT: Amazon has many libs you can use to do this.
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:filename, :key)
    end

    def s3_policy(secret, bucket)
      policy = {
        "expiration" => 20.minutes.from_now.utc.xmlschema,
        "conditions" =>  [ 
          { "bucket" =>  bucket },
          ["starts-with", "$key", secret],
          { "acl" => "public-read" },
          {"redirect"=> uploads_url },
          ["content-length-range", 0, 20485760]
        ]
      }
      Base64.encode64(policy.to_json).gsub(/\n/, '')
    end

    def s3_sign_policy(policy_document, aws_secret_key)
      Base64.encode64(
        OpenSSL::HMAC.digest(
          OpenSSL::Digest::Digest.new('sha1'),
          aws_secret_key,
          policy_document
        )
      ).gsub("\n", "")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrowserUpload</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/uploads/_form.html.erb
<!-- would not be hard to make less ugly templates than this. -->
<form id= "fileUpload">


  File to upload to S3: 
  <input id="file" name="file" type="file"> 
  <br> 
  <input type="submit" value="Upload"> 
</form>

<div style="height:24px; width:100; padding: 3px;">
  <div id="progress" style="background:#718894; width:0%; height:100%; -webkit-border-radius: 3px 3px;"></div>
</div>

<script type="text/javascript">
  $(document).ready( function() {
    var form = $('#fileUpload'),
        progress = $('#progress'),
        data = {};

    form.submit(function(event) {
      event.preventDefault();

      var file = $('#file');
      var fileName = file.val().replace(/C:\\fakepath\\/i, ''); // IE is yuk

      console.log(JSON.stringify(fileName));
      progress.text('Starting to upload file:' + fileName);
      data = { 'key': '<%= @key %>/${filename}',
               'AWSAccessKeyId': '<%= @id %>',
               'acl': 'public-read',
               'redirect': '<%= @callback %>',
               'policy': '<%= @policy %>',
               'signature': '<%= @signature %>'
             };

      $.ajax( {
        dataType: 'iframe',
        iframe: true,
        fileInput: file,
        processData: true,
        contentType: false,
        type: 'POST',
        url: '<%= AWS_HOST %>',
        formData: data,
        xhrFields: {
          withCredentials: true
        },

        complete: function(response) {
          progress.css('width', '0%');
          progress.text('File upload done. Sending callback.');
          console.log(response);
          $.ajax( {
            type: 'POST',
            url: '<%= @callback %>',
            dataType: 'json',
            data: {upload: {filename: fileName, key: '<%= @key %>'}},
            success: function(response) {
              progress.text('Finished.');
              console.log(response);
              form.hide();
            }
          });
        }
      });
    });
  });
</script>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Url</th>
      <th>Key</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
    <tr>
      <td><%= upload.filename %></td>
      <td><a href='<%= upload.url %>'><%= upload.url %></a></td>
      <td><%= upload.key %></td>
      <td><%= link_to 'Show', upload %></td>
      <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @upload.filename %>
</p>

</p>
   <strong>Key:</strong>
  <%= @upload.key %>
</p>

<p>
  <strong>Url:</strong>
  <a href='<%= @upload.url %>'><%= @upload.url %></a>
</p>

<%= link_to 'Back', uploads_path %>